-- MySQL Script generated by MySQL Workbench
-- Tue Feb 14 18:09:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Huddle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Huddle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Huddle` DEFAULT CHARACTER SET utf8 ;
USE `Huddle` ;

-- -----------------------------------------------------
-- Table `Huddle`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Huddle`.`User` ;

CREATE TABLE IF NOT EXISTS `Huddle`.`User` (
  `UserID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Huddle`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Huddle`.`Team` ;

CREATE TABLE IF NOT EXISTS `Huddle`.`Team` (
  `TeamID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`TeamID`),
  UNIQUE INDEX `TeamID_UNIQUE` (`TeamID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Huddle`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Huddle`.`Post` ;

CREATE TABLE IF NOT EXISTS `Huddle`.`Post` (
  `PostID` INT NOT NULL,
  `Content` VARCHAR(2000) NULL,
  `NumberOfLikes` INT NULL,
  `User_UserID` INT NOT NULL,
  `Team_TeamID` INT NOT NULL,
  PRIMARY KEY (`PostID`),
  UNIQUE INDEX `PostID_UNIQUE` (`PostID` ASC) VISIBLE,
  INDEX `fk_Post_User_idx` (`User_UserID` ASC) VISIBLE,
  INDEX `fk_Post_Team1_idx` (`Team_TeamID` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `Huddle`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Team1`
    FOREIGN KEY (`Team_TeamID`)
    REFERENCES `Huddle`.`Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Huddle`.`UserSubscribtion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Huddle`.`UserSubscribtion` ;

CREATE TABLE IF NOT EXISTS `Huddle`.`UserSubscribtion` (
  `User_UserID` INT NOT NULL,
  `Team_TeamID` INT NOT NULL,
  PRIMARY KEY (`User_UserID`, `Team_TeamID`),
  INDEX `fk_User_has_Team_Team1_idx` (`Team_TeamID` ASC) VISIBLE,
  INDEX `fk_User_has_Team_User1_idx` (`User_UserID` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Team_User1`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `Huddle`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Team_Team1`
    FOREIGN KEY (`Team_TeamID`)
    REFERENCES `Huddle`.`Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
